# Generated by Django 4.0.5 on 2022-06-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESB_api', '0003_alter_clientes_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cedula',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
