# Generated by Django 4.0.5 on 2022-06-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESB_api', '0004_alter_clientes_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
    ]
