# Generated by Django 4.0.5 on 2022-06-14 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ESB_api', '0008_factura_producto_tienda_remove_documento_cliente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={'ordering': ['id']},
        ),
        migrations.AlterUniqueTogether(
            name='factura',
            unique_together={('id_cliente', 'id')},
        ),
    ]
