# Generated by Django 4.0.5 on 2022-06-14 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ESB_api', '0009_alter_factura_options_alter_factura_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='ESB_api.cliente'),
        ),
    ]
