# Generated by Django 4.0.5 on 2022-06-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESB_api', '0014_alter_mymodel_my_json_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='json_prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_field', models.JSONField(default=dict)),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.DeleteModel(
            name='Prueba_json',
        ),
    ]
